//
// Created by Carmen on 22-Nov-21.
//

#ifndef NEWASSIGNMENT1_BINARYINSERSIONSORT_HPP
#define NEWASSIGNMENT1_BINARYINSERSIONSORT_HPP


class BinaryInsersionSort {

};


#endif //NEWASSIGNMENT1_BINARYINSERSIONSORT_HPP
